### ISSUE TITLE
Will it run on Jesse?

### ISSUE THREAD

**Issue by danb5** [dillonhafer/garage-server-homekit#1]
Will this work on a RPI Zero running Jesse? Also can it control more then one door?

**Comment by dillonhafer** [comment]
Great questions, Sorry for not seeing this message until now. 

**Will this work on a RPI Zero running Jesse?**
I haven't tried on a zero yet, don't see why it wouldn't.

**Can it control more then one door?**
The software currently only supports one door, but the module I use has two relays. You could just run multiple servers and provide different pins for each server:

```
./garage-server-homekit -relay-pin=10

./garage-server-homekit -relay-pin=11
```

**Comment by WingedToaster** [comment]
Confirmed it works on a RPi Zero running latest Raspbian

**Comment by dillonhafer** [comment]
Awesome! Thanks for testing that! ❤️
